### ISSUE TITLE
Implement support for OBS multiplatform

### ISSUE THREAD

**Issue by AJAnderson** [mparkms/nodecg-for-smash#2]
Hi, any plans to support multiplatform soon? Or are you dependant on NodeCG updating their infrastructure?

**Comment by AJAnderson** [comment]
Did some of my own research and I think it's just a matter of creating a scene in OBS MP and saving it in the obs dir. But I'm not sure if you dynamically generate the scene? I did notice that the elements appear to change size as you update them.

On a second note, do you know why sometimes scrollbars appear on the sides of elements being rendered?

**Comment by mparkms** [comment]
There's no reason why it wouldn't work in OBS-MP. It just lacks the ability to import scenes so you'll have to add the sources manually. It would probably help if you had regular OBS also open and looked at the widths and heights of the sources in there.

As for the scrollbars, they should disappear if you enter the following in the source's CSS section:

```
body {
    overflow: hidden;
}
```

**Comment by AJAnderson** [comment]
Sweet, thank you, issue can be closed. It might be a good idea to add something to the readme about needing to create your own scene if you want to work with MP. Also the stuff about overflow (I noticed the same thing happening in my install of regular OBS).

**Comment by mparkms** [comment]
In regular OBS the scrollbars go away once you've updated from the dashboard. Odd bug, but I think it's something to do with the browser plugin.

**Comment by AJAnderson** [comment]
Yeah I had a suspicion it might be because of that. Unfortunately the plugin ecosystem around MP is pretty bad. I think I should add that to my PR re: the readme actually. (No OBS remote)
